# Generated by Django 3.2 on 2023-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updatede_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
